# ------------------------
# variables.tf
# ------------------------

# GCP project & region
variable "project_id" {
  description = "GCP Project ID"
  type        = string
}

variable "region" {
  description = "GCP Region for resources"
  type        = string
  default     = "us-central1"
}

variable "zone" {
  description = "GCP zone for VM"
  type        = string
  default     = "us-central1-a"
}

# Alerting
variable "alert_email" {
  description = "Email for alert notifications"
  type        = string
}

# Bindplane
variable "bindplane_api_key" {
  description = "BindPlane API key generated by GitHub Actions"
  type        = string
  sensitive   = true
}

variable "bindplane_admin_username" {
  description = "Bindplane admin username"
  type        = string
  default     = "admin"
}

variable "bindplane_admin_password" {
  description = "Bindplane admin password"
  type        = string
  sensitive   = true
}

# Cloud SQL / Postgres
variable "db_name" {
  description = "Cloud SQL database name for Bindplane"
  type        = string
  default     = "bindplane"
}

variable "db_user" {
  description = "Cloud SQL Postgres username"
  type        = string
  default     = "bindplane"
}

variable "db_password" {
  description = "Cloud SQL Postgres user password"
  type        = string
  sensitive   = true
}

# VM Configuration
variable "vm_machine_type" {
  description = "GCP VM machine type for Bindplane"
  type        = string
  default     = "e2-standard-4"
}

variable "vm_boot_disk_size" {
  description = "VM boot disk size in GB"
  type        = number
  default     = 50
}

# GCS / GCO
variable "gcs_bucket_name" {
  description = "GCS bucket name for Bindplane storage / pipeline"
  type        = string
}

# Pipeline / agent
variable "bindplane_agent_name" {
  description = "Name for Bindplane agent"
  type        = string
  default     = "agent-1"
}

variable "pipeline_name" {
  description = "Name for Bindplane pipeline"
  type        = string
  default     = "pipeline-1"
}
